# Generated by Django 6.0.5 on 2026-05-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_index', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct emissions'), ('2', 'Scope 2 — Purchased electricity/heat'), ('3', 'Scope 3 — Value chain')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('raw_quantity', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_date', models.CharField(max_length=50)),
                ('raw_period_start', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_period_end', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_plant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_material_code', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_tariff', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_origin', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_destination', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_travel_class', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_category', models.CharField(blank=True, choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_taxi', 'Ground — Taxi/Rideshare'), ('ground_rail', 'Ground — Rail'), ('ground_rental', 'Ground — Car Rental')], max_length=20, null=True)),
                ('normalized_quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=20)),
                ('activity_date', models.DateField()),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200, null=True)),
                ('co2e_kg', models.FloatField(blank=True, null=True)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INGESTED', 'Ingested'), ('FLAGGED', 'Flagged as suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited'), ('REOPENED', 'Reopened')], max_length=20)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('source_identifier', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('failed_row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FailedRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_rows', to='emissions.ingestionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='emissions.ingestionbatch'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company', 'source_type'], name='emissions_e_company_350279_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company', 'scope'], name='emissions_e_company_92286d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['status'], name='emissions_e_status_035f31_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['suspicious'], name='emissions_e_suspici_cfae19_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'),
        ),
    ]
